### PR TITLE
Update tag list for the release of 20.0.0.9

### PR DESCRIPTION
**Pull request by crpotter**
Remove the old 20.0.0.3 tag information and add in the new 20.0.0.9 tag information.

### CODE REVIEW

**Review by arthurdm — APPROVED** [review]
LGTM

**Comment by artberger** [comment]
Thanks @crpotter . Unfortunately this production repo is protected, but I opened a [mirror PR in our GHE repo here](https://github.ibm.com/cloud-docs/RegistryImages/pull/168) and will promote the PR from there to prod. I'm going to close this one here.

**Comment by artberger** [comment]
The doc is in prod, FYI: https://cloud.ibm.com/docs/RegistryImages?topic=RegistryImages-ibmliberty#ibmliberty_tags

**Comment by arthurdm** [comment]
thanks @artberger / @crpotter!

**Pull request closed without merging**
